# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
 - script: |
      pip install flake8 pylint
      flake8 mypackage/  # Adjust the path to your package's source code
      pylint mypackage/  # Adjust the path to your package's source code
    displayName: 'Code Quality Analysis'

  - script: |
      pip install coverage
      coverage run -m pytest
      coverage report -m
    displayName: 'Code Coverage'

  - script: |
      pip install twine
      python setup.py sdist bdist_wheel
      twine upload dist/*
    displayName: 'Publish to PyPI'
    condition: succeeded()  # Only publish if previous steps succeed